// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: API/session.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLiftRequestFeeler int32

const (
	AddLiftRequest_UNKNOWN AddLiftRequestFeeler = 0
	AddLiftRequest_BAD     AddLiftRequestFeeler = 1
	AddLiftRequest_OK      AddLiftRequestFeeler = 2
	AddLiftRequest_GOOD    AddLiftRequestFeeler = 3
)

// Enum value maps for AddLiftRequestFeeler.
var (
	AddLiftRequestFeeler_name = map[int32]string{
		0: "UNKNOWN",
		1: "BAD",
		2: "OK",
		3: "GOOD",
	}
	AddLiftRequestFeeler_value = map[string]int32{
		"UNKNOWN": 0,
		"BAD":     1,
		"OK":      2,
		"GOOD":    3,
	}
)

func (x AddLiftRequestFeeler) Enum() *AddLiftRequestFeeler {
	p := new(AddLiftRequestFeeler)
	*p = x
	return p
}

func (x AddLiftRequestFeeler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddLiftRequestFeeler) Descriptor() protoreflect.EnumDescriptor {
	return file_API_session_proto_enumTypes[0].Descriptor()
}

func (AddLiftRequestFeeler) Type() protoreflect.EnumType {
	return &file_API_session_proto_enumTypes[0]
}

func (x AddLiftRequestFeeler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddLiftRequestFeeler.Descriptor instead.
func (AddLiftRequestFeeler) EnumDescriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{0, 0}
}

type AddRunRequestFeeler int32

const (
	AddRunRequest_UNKNOWN AddRunRequestFeeler = 0
	AddRunRequest_BAD     AddRunRequestFeeler = 1
	AddRunRequest_OK      AddRunRequestFeeler = 2
	AddRunRequest_GOOD    AddRunRequestFeeler = 3
)

// Enum value maps for AddRunRequestFeeler.
var (
	AddRunRequestFeeler_name = map[int32]string{
		0: "UNKNOWN",
		1: "BAD",
		2: "OK",
		3: "GOOD",
	}
	AddRunRequestFeeler_value = map[string]int32{
		"UNKNOWN": 0,
		"BAD":     1,
		"OK":      2,
		"GOOD":    3,
	}
)

func (x AddRunRequestFeeler) Enum() *AddRunRequestFeeler {
	p := new(AddRunRequestFeeler)
	*p = x
	return p
}

func (x AddRunRequestFeeler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddRunRequestFeeler) Descriptor() protoreflect.EnumDescriptor {
	return file_API_session_proto_enumTypes[1].Descriptor()
}

func (AddRunRequestFeeler) Type() protoreflect.EnumType {
	return &file_API_session_proto_enumTypes[1]
}

func (x AddRunRequestFeeler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddRunRequestFeeler.Descriptor instead.
func (AddRunRequestFeeler) EnumDescriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{2, 0}
}

type AddSessionRequest_SessionType int32

const (
	AddSessionRequest_UNKNOWN AddSessionRequest_SessionType = 0
	AddSessionRequest_LIFT    AddSessionRequest_SessionType = 1
	AddSessionRequest_RUN     AddSessionRequest_SessionType = 2
)

// Enum value maps for AddSessionRequest_SessionType.
var (
	AddSessionRequest_SessionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "LIFT",
		2: "RUN",
	}
	AddSessionRequest_SessionType_value = map[string]int32{
		"UNKNOWN": 0,
		"LIFT":    1,
		"RUN":     2,
	}
)

func (x AddSessionRequest_SessionType) Enum() *AddSessionRequest_SessionType {
	p := new(AddSessionRequest_SessionType)
	*p = x
	return p
}

func (x AddSessionRequest_SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddSessionRequest_SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_API_session_proto_enumTypes[2].Descriptor()
}

func (AddSessionRequest_SessionType) Type() protoreflect.EnumType {
	return &file_API_session_proto_enumTypes[2]
}

func (x AddSessionRequest_SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddSessionRequest_SessionType.Descriptor instead.
func (AddSessionRequest_SessionType) EnumDescriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{4, 0}
}

type AddLiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string               `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Workout   string               `protobuf:"bytes,2,opt,name=workout,proto3" json:"workout,omitempty"`
	Weight    string               `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Feel      AddLiftRequestFeeler `protobuf:"varint,4,opt,name=feel,proto3,enum=AddLiftRequestFeeler" json:"feel,omitempty"`
}

func (x *AddLiftRequest) Reset() {
	*x = AddLiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLiftRequest) ProtoMessage() {}

func (x *AddLiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLiftRequest.ProtoReflect.Descriptor instead.
func (*AddLiftRequest) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{0}
}

func (x *AddLiftRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddLiftRequest) GetWorkout() string {
	if x != nil {
		return x.Workout
	}
	return ""
}

func (x *AddLiftRequest) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *AddLiftRequest) GetFeel() AddLiftRequestFeeler {
	if x != nil {
		return x.Feel
	}
	return AddLiftRequest_UNKNOWN
}

type AddLiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddLiftResponse) Reset() {
	*x = AddLiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLiftResponse) ProtoMessage() {}

func (x *AddLiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLiftResponse.ProtoReflect.Descriptor instead.
func (*AddLiftResponse) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{1}
}

type AddRunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string              `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Time      string              `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Distance  string              `protobuf:"bytes,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Feel      AddRunRequestFeeler `protobuf:"varint,4,opt,name=feel,proto3,enum=AddRunRequestFeeler" json:"feel,omitempty"`
}

func (x *AddRunRequest) Reset() {
	*x = AddRunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRunRequest) ProtoMessage() {}

func (x *AddRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRunRequest.ProtoReflect.Descriptor instead.
func (*AddRunRequest) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{2}
}

func (x *AddRunRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddRunRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AddRunRequest) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *AddRunRequest) GetFeel() AddRunRequestFeeler {
	if x != nil {
		return x.Feel
	}
	return AddRunRequest_UNKNOWN
}

type AddRunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRunResponse) Reset() {
	*x = AddRunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRunResponse) ProtoMessage() {}

func (x *AddRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRunResponse.ProtoReflect.Descriptor instead.
func (*AddRunResponse) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{3}
}

type AddSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type AddSessionRequest_SessionType `protobuf:"varint,1,opt,name=type,proto3,enum=AddSessionRequest_SessionType" json:"type,omitempty"`
}

func (x *AddSessionRequest) Reset() {
	*x = AddSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionRequest) ProtoMessage() {}

func (x *AddSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionRequest.ProtoReflect.Descriptor instead.
func (*AddSessionRequest) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{4}
}

func (x *AddSessionRequest) GetType() AddSessionRequest_SessionType {
	if x != nil {
		return x.Type
	}
	return AddSessionRequest_UNKNOWN
}

type AddSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddSessionResponse) Reset() {
	*x = AddSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionResponse) ProtoMessage() {}

func (x *AddSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionResponse.ProtoReflect.Descriptor instead.
func (*AddSessionResponse) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{5}
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date   string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	SeshId string `protobuf:"bytes,2,opt,name=sesh_id,json=seshId,proto3" json:"sesh_id,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{6}
}

func (x *Session) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Session) GetSeshId() string {
	if x != nil {
		return x.SeshId
	}
	return ""
}

var File_API_session_proto protoreflect.FileDescriptor

var file_API_session_proto_rawDesc = []byte{
	0x0a, 0x11, 0x41, 0x50, 0x49, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x66, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x52, 0x04, 0x66,
	0x65, 0x65, 0x6c, 0x22, 0x30, 0x0a, 0x06, 0x66, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41,
	0x44, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x47,
	0x4f, 0x4f, 0x44, 0x10, 0x03, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x64,
	0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x65, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x66, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x52, 0x04,
	0x66, 0x65, 0x65, 0x6c, 0x22, 0x30, 0x0a, 0x06, 0x66, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42,
	0x41, 0x44, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x47, 0x4f, 0x4f, 0x44, 0x10, 0x03, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x76, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x2d, 0x0a, 0x0b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x4c, 0x49, 0x46, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x55, 0x4e, 0x10, 0x02,
	0x22, 0x14, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x68, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x73, 0x68, 0x49, 0x64, 0x32, 0xa8,
	0x01, 0x0a, 0x12, 0x4c, 0x69, 0x66, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74, 0x12, 0x0f, 0x2e, 0x41, 0x64, 0x64, 0x4c,
	0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x41, 0x64, 0x64,
	0x4c, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x29,
	0x0a, 0x06, 0x61, 0x64, 0x64, 0x52, 0x75, 0x6e, 0x12, 0x0e, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x75,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x75,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_API_session_proto_rawDescOnce sync.Once
	file_API_session_proto_rawDescData = file_API_session_proto_rawDesc
)

func file_API_session_proto_rawDescGZIP() []byte {
	file_API_session_proto_rawDescOnce.Do(func() {
		file_API_session_proto_rawDescData = protoimpl.X.CompressGZIP(file_API_session_proto_rawDescData)
	})
	return file_API_session_proto_rawDescData
}

var file_API_session_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_API_session_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_API_session_proto_goTypes = []interface{}{
	(AddLiftRequestFeeler)(0),          // 0: AddLiftRequest.feeler
	(AddRunRequestFeeler)(0),           // 1: AddRunRequest.feeler
	(AddSessionRequest_SessionType)(0), // 2: AddSessionRequest.SessionType
	(*AddLiftRequest)(nil),             // 3: AddLiftRequest
	(*AddLiftResponse)(nil),            // 4: AddLiftResponse
	(*AddRunRequest)(nil),              // 5: AddRunRequest
	(*AddRunResponse)(nil),             // 6: AddRunResponse
	(*AddSessionRequest)(nil),          // 7: AddSessionRequest
	(*AddSessionResponse)(nil),         // 8: AddSessionResponse
	(*Session)(nil),                    // 9: Session
}
var file_API_session_proto_depIdxs = []int32{
	0, // 0: AddLiftRequest.feel:type_name -> AddLiftRequest.feeler
	1, // 1: AddRunRequest.feel:type_name -> AddRunRequest.feeler
	2, // 2: AddSessionRequest.type:type_name -> AddSessionRequest.SessionType
	7, // 3: LiftSessionService.addSession:input_type -> AddSessionRequest
	3, // 4: LiftSessionService.addLift:input_type -> AddLiftRequest
	5, // 5: LiftSessionService.addRun:input_type -> AddRunRequest
	8, // 6: LiftSessionService.addSession:output_type -> AddSessionResponse
	4, // 7: LiftSessionService.addLift:output_type -> AddLiftResponse
	6, // 8: LiftSessionService.addRun:output_type -> AddRunResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_API_session_proto_init() }
func file_API_session_proto_init() {
	if File_API_session_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_API_session_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_API_session_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_API_session_proto_goTypes,
		DependencyIndexes: file_API_session_proto_depIdxs,
		EnumInfos:         file_API_session_proto_enumTypes,
		MessageInfos:      file_API_session_proto_msgTypes,
	}.Build()
	File_API_session_proto = out.File
	file_API_session_proto_rawDesc = nil
	file_API_session_proto_goTypes = nil
	file_API_session_proto_depIdxs = nil
}
