// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.0
// source: API/session.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLiftRequestFeeler int32

const (
	AddLiftRequest_UNKNOWN AddLiftRequestFeeler = 0
	AddLiftRequest_BAD     AddLiftRequestFeeler = 1
	AddLiftRequest_OK      AddLiftRequestFeeler = 2
	AddLiftRequest_GOOD    AddLiftRequestFeeler = 3
)

// Enum value maps for AddLiftRequestFeeler.
var (
	AddLiftRequestFeeler_name = map[int32]string{
		0: "UNKNOWN",
		1: "BAD",
		2: "OK",
		3: "GOOD",
	}
	AddLiftRequestFeeler_value = map[string]int32{
		"UNKNOWN": 0,
		"BAD":     1,
		"OK":      2,
		"GOOD":    3,
	}
)

func (x AddLiftRequestFeeler) Enum() *AddLiftRequestFeeler {
	p := new(AddLiftRequestFeeler)
	*p = x
	return p
}

func (x AddLiftRequestFeeler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddLiftRequestFeeler) Descriptor() protoreflect.EnumDescriptor {
	return file_API_session_proto_enumTypes[0].Descriptor()
}

func (AddLiftRequestFeeler) Type() protoreflect.EnumType {
	return &file_API_session_proto_enumTypes[0]
}

func (x AddLiftRequestFeeler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddLiftRequestFeeler.Descriptor instead.
func (AddLiftRequestFeeler) EnumDescriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{0, 0}
}

type AddLiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string               `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Workout   string               `protobuf:"bytes,2,opt,name=workout,proto3" json:"workout,omitempty"`
	Weight    int64                `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Feel      AddLiftRequestFeeler `protobuf:"varint,4,opt,name=feel,proto3,enum=AddLiftRequestFeeler" json:"feel,omitempty"`
}

func (x *AddLiftRequest) Reset() {
	*x = AddLiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLiftRequest) ProtoMessage() {}

func (x *AddLiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLiftRequest.ProtoReflect.Descriptor instead.
func (*AddLiftRequest) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{0}
}

func (x *AddLiftRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddLiftRequest) GetWorkout() string {
	if x != nil {
		return x.Workout
	}
	return ""
}

func (x *AddLiftRequest) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *AddLiftRequest) GetFeel() AddLiftRequestFeeler {
	if x != nil {
		return x.Feel
	}
	return AddLiftRequest_UNKNOWN
}

type AddLiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lift *Lift `protobuf:"bytes,1,opt,name=lift,proto3" json:"lift,omitempty"`
}

func (x *AddLiftResponse) Reset() {
	*x = AddLiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLiftResponse) ProtoMessage() {}

func (x *AddLiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLiftResponse.ProtoReflect.Descriptor instead.
func (*AddLiftResponse) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{1}
}

func (x *AddLiftResponse) GetLift() *Lift {
	if x != nil {
		return x.Lift
	}
	return nil
}

type Lift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Lift      string `protobuf:"bytes,2,opt,name=lift,proto3" json:"lift,omitempty"`
	Weight    int64  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Feel      string `protobuf:"bytes,4,opt,name=feel,proto3" json:"feel,omitempty"`
}

func (x *Lift) Reset() {
	*x = Lift{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lift) ProtoMessage() {}

func (x *Lift) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lift.ProtoReflect.Descriptor instead.
func (*Lift) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{2}
}

func (x *Lift) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Lift) GetLift() string {
	if x != nil {
		return x.Lift
	}
	return ""
}

func (x *Lift) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Lift) GetFeel() string {
	if x != nil {
		return x.Feel
	}
	return ""
}

type AddSessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddSessionRequest) Reset() {
	*x = AddSessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionRequest) ProtoMessage() {}

func (x *AddSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionRequest.ProtoReflect.Descriptor instead.
func (*AddSessionRequest) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{3}
}

type AddSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
}

func (x *AddSessionResponse) Reset() {
	*x = AddSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionResponse) ProtoMessage() {}

func (x *AddSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionResponse.ProtoReflect.Descriptor instead.
func (*AddSessionResponse) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{4}
}

func (x *AddSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date   string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	SeshId string `protobuf:"bytes,2,opt,name=sesh_id,json=seshId,proto3" json:"sesh_id,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_API_session_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_API_session_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_API_session_proto_rawDescGZIP(), []int{5}
}

func (x *Session) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Session) GetSeshId() string {
	if x != nil {
		return x.SeshId
	}
	return ""
}

var File_API_session_proto protoreflect.FileDescriptor

var file_API_session_proto_rawDesc = []byte{
	0x0a, 0x11, 0x41, 0x50, 0x49, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x75, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x66, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x52, 0x04, 0x66,
	0x65, 0x65, 0x6c, 0x22, 0x30, 0x0a, 0x06, 0x66, 0x65, 0x65, 0x6c, 0x65, 0x72, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41,
	0x44, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x47,
	0x4f, 0x4f, 0x44, 0x10, 0x03, 0x22, 0x2c, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x04, 0x6c, 0x69, 0x66, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4c, 0x69, 0x66, 0x74, 0x52, 0x04, 0x6c,
	0x69, 0x66, 0x74, 0x22, 0x65, 0x0a, 0x04, 0x4c, 0x69, 0x66, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69,
	0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x66, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x65, 0x65, 0x6c, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x38, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x07, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x68,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x73, 0x68, 0x49,
	0x64, 0x32, 0x79, 0x0a, 0x12, 0x4c, 0x69, 0x66, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x41, 0x64, 0x64, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x4c, 0x69, 0x66, 0x74, 0x12, 0x0f, 0x2e, 0x41, 0x64, 0x64, 0x4c,
	0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x41, 0x64, 0x64,
	0x4c, 0x69, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_API_session_proto_rawDescOnce sync.Once
	file_API_session_proto_rawDescData = file_API_session_proto_rawDesc
)

func file_API_session_proto_rawDescGZIP() []byte {
	file_API_session_proto_rawDescOnce.Do(func() {
		file_API_session_proto_rawDescData = protoimpl.X.CompressGZIP(file_API_session_proto_rawDescData)
	})
	return file_API_session_proto_rawDescData
}

var file_API_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_API_session_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_API_session_proto_goTypes = []interface{}{
	(AddLiftRequestFeeler)(0),  // 0: AddLiftRequest.feeler
	(*AddLiftRequest)(nil),     // 1: AddLiftRequest
	(*AddLiftResponse)(nil),    // 2: AddLiftResponse
	(*Lift)(nil),               // 3: Lift
	(*AddSessionRequest)(nil),  // 4: AddSessionRequest
	(*AddSessionResponse)(nil), // 5: AddSessionResponse
	(*Session)(nil),            // 6: Session
}
var file_API_session_proto_depIdxs = []int32{
	0, // 0: AddLiftRequest.feel:type_name -> AddLiftRequest.feeler
	3, // 1: AddLiftResponse.lift:type_name -> Lift
	6, // 2: AddSessionResponse.Session:type_name -> Session
	4, // 3: LiftSessionService.addSession:input_type -> AddSessionRequest
	1, // 4: LiftSessionService.addLift:input_type -> AddLiftRequest
	5, // 5: LiftSessionService.addSession:output_type -> AddSessionResponse
	2, // 6: LiftSessionService.addLift:output_type -> AddLiftResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_API_session_proto_init() }
func file_API_session_proto_init() {
	if File_API_session_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_API_session_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_API_session_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_API_session_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_API_session_proto_goTypes,
		DependencyIndexes: file_API_session_proto_depIdxs,
		EnumInfos:         file_API_session_proto_enumTypes,
		MessageInfos:      file_API_session_proto_msgTypes,
	}.Build()
	File_API_session_proto = out.File
	file_API_session_proto_rawDesc = nil
	file_API_session_proto_goTypes = nil
	file_API_session_proto_depIdxs = nil
}
